services:
  100pfps:
    image: 100pfps
    container_name: 100pfps
    build: 
      dockerfile: ./Dockerfile.prod
      context: .
      args:
        UNAME: ${UNAME}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@100pfps-db-prod/${POSTGRES_DB}
      - MODE=${MODE}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - 8080:8080

  db:
    image: docker.io/postgres:alpine
    container_name: 100pfps-db-prod
    restart: unless-stopped
    volumes: 
      - db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U${POSTGRES_USER}"]
      interval: 10m
      start_period: 10s
      start_interval: 3s

volumes:
  db:
    name: 100pfps-db-prod
